# Generated by Django 4.2.3 on 2023-11-06 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Фото профиля')),
                ('access', models.CharField(choices=[('sm', 'service_man'), ('sa', 'service_admin'), ('rm', 'risola_manager'), ('ad', 'another_driver'), ('fa', 'full_access')], default='rm', max_length=2, verbose_name='Уровень доступа')),
                ('show_weeks', models.IntegerField(choices=[(1, 'One Week'), (2, 'Two Weeks')], default=1, verbose_name='Отображать недель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
