# Generated by Django 4.2.3 on 2024-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risola_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
