# Generated by Django 4.2.3 on 2023-11-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(default=0, verbose_name='Object_id в системе nav.by')),
            ],
        ),
        migrations.CreateModel(
            name='CarServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report', models.FileField(upload_to='reports')),
            ],
        ),
        migrations.CreateModel(
            name='CarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('engineer', models.CharField(default='', max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('taking_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('km_per_day', models.IntegerField(default=0, verbose_name='Пробег за день (км)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.car')),
            ],
        ),
    ]
