# Generated by Django 4.2.3 on 2023-07-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnote',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.profile'),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='return_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='taking_time',
            field=models.TimeField(null=True),
        ),
    ]
