# Generated by Django 4.2.3 on 2024-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_mileage',
            field=models.FloatField(default=0, verbose_name='Текущий пробег, км'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_maintenance_mileage',
            field=models.FloatField(default=0, verbose_name='Пробег при последнем ТО, км'),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_frequency',
            field=models.FloatField(default=15000, verbose_name='Частота ТО, км'),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='km_per_day',
            field=models.FloatField(default=0, verbose_name='Пробег за день, км)'),
        ),
    ]
