# Generated by Django 4.2.3 on 2023-07-31 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnote',
            name='profile',
        ),
        migrations.AddField(
            model_name='carnote',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carnote',
            name='taking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
