# Generated by Django 4.2.3 on 2023-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_carnote_profile_carnote_engineer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnote',
            name='engineer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
