# Generated by Django 4.2.3 on 2023-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_carnote_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report', models.FileField(upload_to='reports')),
            ],
        ),
    ]
