# Generated by Django 4.2.3 on 2023-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_carserviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnote',
            name='km_per_day',
            field=models.IntegerField(default=0, verbose_name='Пробег за день (км)'),
        ),
    ]
