# Generated by Django 4.2.3 on 2023-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_carnote_km_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='object_id',
            field=models.IntegerField(default=0, verbose_name='Object_id в системе nav.by'),
        ),
    ]
